@startwbs ProjectFolderStructure

!theme blueprint

title
    Estrutura de pastas da Infraestrutura Kubernetes
end title

* TechChallengeK8s
**_ food-delivery
***_ config
****_ database-api-secrets.yaml
****_ main-api-secrets.yaml
***_ deployment
****_ database-api-deployment.yaml
****_ main-api-deployment.yaml
***_ horizontal-pod-autoscaler
****_ main-api-hpa.yaml
***_ persistent-volume
****_ postgres-pv.yaml
***_ persistent-volume-claim
****_ postgres-pvc.yaml
***_ service
****_ main-api-service.yaml
****_ postgres-api-service.yaml

@endwbs