apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-api-v2-config
data:
  POSTGRES_DB: fiap_db
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: Senha48
  POSTGRES_PORT: "5432"
  POSTGRES_URL: postgresql://postgres:5432/fiap_db
  SERVER_PORT: "8081"
  LOG_LEVEL: INFO
  LOG_PATH: logs/grupo48.log
  SPRING_PROFILE: production