apiVersion: v1
kind: ConfigMap
metadata:
  name: tech-challenge-4soat-g48-api-config
data:
  APP_ENV: production
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tc_soat4_g48
  SPRING_DATASOURCE_USERNAME: admin
  SPRING_DATASOURCE_PASSWORD: senha48