apiVersion: v1
kind: Service
metadata:
  name: kubernetes-api-v2
spec:
  selector:
    app: kubernetes-api-v2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer