apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tech-challenge-4soat-g48-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tech-challenge-4soat-g48-api
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50