apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kubernetes-api-v1-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kubernetes-api-v1
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50