apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-api-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-api-v1
  template:
    metadata:
      labels:
        app: kubernetes-api-v1
    spec:
      containers:
      - name: kubernetes-api-v1
        image: mateuslima/fiap_api:v2
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: kubernetes-api-v1-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"